In [1]:
!pip install polars

Collecting polars
  Using cached polars-1.38.1-py3-none-any.whl.metadata (10 kB)
Collecting polars-runtime-32==1.38.1 (from polars)
  Using cached polars_runtime_32-1.38.1-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Using cached polars-1.38.1-py3-none-any.whl (810 kB)
Using cached polars_runtime_32-1.38.1-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (45.8 MB)
Installing collected packages: polars-runtime-32, polars
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [polars]2m1/2 [polars]
Successfully installed polars-1.38.1 polars-runtime-32-1.38.1

In [2]:
import polars as pl
import seaborn as sns
import matplotlib.pyplot as plt
import math
import pandas as pd

## Read data from S3 and join

In [ ]:
source_bucket = 's3://msds-26.2-data'
file_names = ['sanitized_2022.csv', 'sanitized_2023.csv', 'sanitized_2024.csv', 'sanitized_2025.csv']

In [ ]:
# Read csv from s3 and concat
df_recovery = pl.DataFrame()
for name in file_names:
    file_path = f'{source_bucket}/{name}'
    df_name = pl.read_csv(file_path, separator="\t")
    df_recovery = pl.concat([df_recovery, df_name])

In [ ]:
del df_name

In [ ]:
len(df_recovery)

## Data Cleaning

In [ ]:
# Drop columns where all values are null
cols_to_drop = (
    df_recovery.select(pl.all().is_null().all())
    .unpivot()
    .filter(pl.col("value") == True)
    .select("variable")
    .to_series()
    .to_list()
)

# Drop the identified columns from the original DataFrame
df_recovery = df_recovery.drop(cols_to_drop)

In [ ]:
# Remove all C-Returns from the data
df_recovery = df_recovery.filter(pl.col('recovery_type') != 'C-Returns')

In [ ]:
# Create target variable for propensity to waste model
df_recovery = df_recovery.with_columns(
    pl.when(pl.col('recovery_type') == 'Sales').then(pl.lit(0))
    .otherwise(pl.lit(1)).alias('recovery')
)

In [ ]:
df_recovery.filter(pl.col('country') != pl.col('marketplace_id'))

In [ ]:
# Remove marketplace_id b/c it's a duplicate of country
df_recovery = df_recovery.drop(['marketplace_id'])

In [ ]:
# Reorder the columns
df_recovery = df_recovery.select([
 'hashed_fc',
 'year',
 'month',
 'week',
 'gl_product_group',
 'product_type',
 'macro_category',
 'item_disposition_code',
 'reason_code',
 'application_name',
 'is_stranded',
 'reason_code_type',
 'reason_code_stranded',
 'stranded_potential_issue',
 'is_hazmat',
 'units',
 'cogs',
 'weight',
 'country',
 'country_state',
 'zip_code',
 'site_type',
 'site_category',
 'recovery',
 'recovery_type'])

In [ ]:
df_recovery.null_count()

In [ ]:
len(df_recovery)

In [ ]:
destination = "s3://msds-26.2-data/clean/combined_recovery_data.parquet"
df_recovery.write_parquet(destination)

In [4]:
# Remove 3000 isntances of missing gl_product_group
df_recovery = df_recovery.filter(pl.col('gl_product_group').is_not_null())

In [5]:
df_recovery.describe()

shape: (9, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ hashed_fc ┆ year      ┆ month     ┆ … ┆ site_type ┆ site_cate ┆ recovery  ┆ recovery │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ gory      ┆ ---       ┆ _type    │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ str       ┆ ---       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 55896510  ┆ 5.589651e ┆ 5.589651e ┆ … ┆ 51479053  ┆ 51479053  ┆ 5.589651e ┆ 55896510 │
│           ┆           ┆ 7         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆          │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 4417457   ┆ 4417457   ┆ 0.0       ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2023.7622 ┆ 6.523622  ┆ … ┆ null      ┆ null      ┆ 0.599529  ┆ null     │
│           ┆           ┆ 83        ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ 1.0951    ┆ 3.438518  ┆ … ┆ null      ┆ null      ┆ 0.489994  ┆ null     │
│ min       ┆ 0000c60d3 ┆ 2022.0    ┆ 1.0       ┆ … ┆ 3rd Party ┆ AMXL      ┆ 0.0       ┆ Bintool  │
│           ┆ b14250deb ┆           ┆           ┆   ┆ Logistics ┆           ┆           ┆ Donation │
│           ┆ 1312b21a4 ┆           ┆           ┆   ┆ (3PL)     ┆           ┆           ┆ s        │
│           ┆ 48a…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2023.0    ┆ 4.0       ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ null     │
│ 50%       ┆ null      ┆ 2024.0    ┆ 7.0       ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ null     │
│ 75%       ┆ null      ┆ 2025.0    ┆ 10.0      ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ null     │
│ max       ┆ fffda6de5 ┆ 2025.0    ┆ 12.0      ┆ … ┆ Zappos    ┆ Other     ┆ 1.0       ┆ Warehous │
│           ┆ ef71646fa ┆           ┆           ┆   ┆           ┆           ┆           ┆ e Deals  │
│           ┆ f113a5359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ and G&R  │
│           ┆ c32…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df_recovery.filter(pl.col('recovery') == 0)['reason_code'].value_counts()
# Only products that enter the recovery funnel have reason code - might not be usable for propensity to waste model

shape: (1, 2)
┌─────────────┬──────────┐
│ reason_code ┆ count    │
│ ---         ┆ ---      │
│ str         ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 22384933 │
└─────────────┴──────────┘

In [15]:
df_recovery.filter(pl.col('recovery') == 0)['is_stranded'].value_counts()
# Only products that enter the recovery funnel are stranded

shape: (1, 2)
┌─────────────┬──────────┐
│ is_stranded ┆ count    │
│ ---         ┆ ---      │
│ str         ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 22384933 │
└─────────────┴──────────┘

In [16]:
df_recovery_agg = df_recovery.group_by(['hashed_fc', 'year', 'month', 'week', 'gl_product_group']).agg(
    pl.len().alias('num_records'),
    ((pl.col('reason_code') == 'E').sum()/pl.len()).alias('proportion_reason_code_E'),
    ((pl.col('reason_code') == 'O').sum()/pl.len()).alias('proportion_reason_code_O'),
    ((pl.col('macro_category') == 'RETAIL').sum()/pl.len()).alias('proportion_macro_category_RETAIL'),
    ((pl.col('macro_category') == 'FBA').sum()/pl.len()).alias('proportion_macro_category_FBA'),
    ((pl.col('is_hazmat') == 'O').sum()/pl.len()).alias('proportion_hazmat'),
    ((pl.col('product_type') == 'Food').sum()/pl.len()).alias('proportion_food'),
    ((pl.col('product_type') == 'Non Food').sum()/pl.len()).alias('proportion_non_food'),
    ((pl.col('product_type') == 'Pet Food').sum()/pl.len()).alias('proportion_pet_food'),
    ((pl.col('is_stranded') == 'Y').sum()/pl.len()).alias('proportion_stranded'),
    ((pl.col('reason_code_type') == 'LLSI').sum()/pl.len()).alias('proportion_reason_code_type_LLSI'),
    ((pl.col('reason_code_type') == '\\N').sum()/pl.len()).alias('proportion_reason_code_type_N'),
    ((pl.col('reason_code_type') == 'MCF').sum()/pl.len()).alias('proportion_reason_code_type_MCF'),
    ((pl.col('reason_code_type') == 'ALSI').sum()/pl.len()).alias('proportion_reason_code_type_ALSI'),
    pl.col('units').sum().alias('units_total'),
    pl.col('units').mean().alias('units_mean'),
    pl.col('units').std().alias('units_std'),
    pl.col('cogs').sum().alias('cogs_total'),
    pl.col('cogs').mean().alias('cogs_mean'),
    pl.col('cogs').std().alias('cogs_std'),
    pl.col('weight').sum().alias('weight_total'),
    pl.col('weight').mean().alias('weight_mean'),
    pl.col('weight').std().alias('weight_std'),
    pl.min('country'),
    pl.min('country_state'),
    pl.min('zip_code'),
    pl.min('site_type'),
    pl.min('site_category'),
    (pl.sum('recovery')/pl.len()).alias('proportion_recovery')
).sort(by='num_records', descending=True)
df_recovery_agg

shape: (8_814_789, 34)
┌───────────────┬──────┬───────┬──────┬───┬──────────┬─────────────┬───────────────┬───────────────┐
│ hashed_fc     ┆ year ┆ month ┆ week ┆ … ┆ zip_code ┆ site_type   ┆ site_category ┆ proportion_re │
│ ---           ┆ ---  ┆ ---   ┆ ---  ┆   ┆ ---      ┆ ---         ┆ ---           ┆ covery        │
│ str           ┆ i64  ┆ i64   ┆ f64  ┆   ┆ str      ┆ str         ┆ str           ┆ ---           │
│               ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆ f64           │
╞═══════════════╪══════╪═══════╪══════╪═══╪══════════╪═════════════╪═══════════════╪═══════════════╡
│ 825f65d7988f0 ┆ 2024 ┆ 6     ┆ 23.0 ┆ … ┆ 91752    ┆ AR Sortable ┆ GCF           ┆ 0.941176      │
│ 20fca7a29b867 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 278d…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 05a669864a534 ┆ 2024 ┆ 3     ┆ 13.0 ┆ … ┆ 85043    ┆ AR Sortable ┆ GCF           ┆ 0.973333      │
│ 498bb4f40f3b7 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 42c4…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 05a669864a534 ┆ 2024 ┆ 3     ┆ 10.0 ┆ … ┆ 85043    ┆ AR Sortable ┆ GCF           ┆ 0.979866      │
│ 498bb4f40f3b7 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 42c4…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 05a669864a534 ┆ 2024 ┆ 3     ┆ 11.0 ┆ … ┆ 85043    ┆ AR Sortable ┆ GCF           ┆ 0.97973       │
│ 498bb4f40f3b7 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 42c4…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 825f65d7988f0 ┆ 2024 ┆ 2     ┆ 8.0  ┆ … ┆ 91752    ┆ AR Sortable ┆ GCF           ┆ 0.931034      │
│ 20fca7a29b867 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 278d…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ …             ┆ …    ┆ …     ┆ …    ┆ … ┆ …        ┆ …           ┆ …             ┆ …             │
│ 5582e5c4aaa5d ┆ 2022 ┆ 9     ┆ 36.0 ┆ … ┆ null     ┆ null        ┆ null          ┆ 0.0           │
│ 1a475e07fe002 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ aa46…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ f5d61f51d1645 ┆ 2023 ┆ 9     ┆ 36.0 ┆ … ┆ null     ┆ null        ┆ null          ┆ 0.0           │
│ bbd602cdf1595 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ b964…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 70332d66a560e ┆ 2022 ┆ 12    ┆ 49.0 ┆ … ┆ null     ┆ null        ┆ null          ┆ 0.0           │
│ e6818f1dde2a5 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 2871…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 8f9dcc5a8b999 ┆ 2023 ┆ 5     ┆ 20.0 ┆ … ┆ null     ┆ null        ┆ null          ┆ 0.0           │
│ ceb9550871338 ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 2045…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ 14b0b99d7df35 ┆ 2024 ┆ 8     ┆ 34.0 ┆ … ┆ null     ┆ null        ┆ null          ┆ 0.0           │
│ feb03e3bba9ec ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
│ a649…         ┆      ┆       ┆      ┆   ┆          ┆             ┆               ┆               │
└───────────────┴──────┴───────┴──────┴───┴──────────┴─────────────┴───────────────┴───────────────┘

In [17]:
destination = "s3://msds-26.2-data/clean/combined_recovery_data_aggregated.parquet"
df_recovery_agg.write_parquet(destination)