In [1]:
!pip install shap polars optuna optuna-integration interpret

Requirement already satisfied: shap in /opt/conda/lib/python3.12/site-packages (0.52.0)
Requirement already satisfied: polars in /opt/conda/lib/python3.12/site-packages (1.41.2)
Requirement already satisfied: optuna in /opt/conda/lib/python3.12/site-packages (4.8.0)
Requirement already satisfied: optuna-integration in /opt/conda/lib/python3.12/site-packages (4.9.0)
Requirement already satisfied: interpret in /opt/conda/lib/python3.12/site-packages (0.7.8)
Requirement already satisfied: numpy>=2 in /opt/conda/lib/python3.12/site-packages (from shap) (2.4.6)
Requirement already satisfied: scipy in /opt/conda/lib/python3.12/site-packages (from shap) (1.16.3)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.12/site-packages (from shap) (1.7.2)
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (from shap) (2.3.3)
Requirement already satisfied: tqdm>=4.27.0 in /opt/conda/lib/python3.12/site-packages (from shap) (4.67.3)
Requirement already satisfied: packaging>20.9 in /opt/conda/lib/python3.12/site-packages (from shap) (24.2)
Requirement already satisfied: slicer==0.0.8 in /opt/conda/lib/python3.12/site-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /opt/conda/lib/python3.12/site-packages (from shap) (0.65.1)
Requirement already satisfied: llvmlite in /opt/conda/lib/python3.12/site-packages (from shap) (0.47.0)
Requirement already satisfied: cloudpickle in /opt/conda/lib/python3.12/site-packages (from shap) (3.1.2)
Requirement already satisfied: polars-runtime-32==1.41.2 in /opt/conda/lib/python3.12/site-packages (from polars) (1.41.2)
Requirement already satisfied: alembic>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /opt/conda/lib/python3.12/site-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /opt/conda/lib/python3.12/site-packages (from optuna) (2.0.49)
Requirement already satisfied: PyYAML in /opt/conda/lib/python3.12/site-packages (from optuna) (6.0.3)
Requirement already satisfied: interpret-core==0.7.8 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.7.8)
Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.12/site-packages (from interpret-core==0.7.8->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.5.3)
Requirement already satisfied: psutil>=5.6.2 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (5.9.8)
Requirement already satisfied: ipython>=5.5.0 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (8.37.0)
Requirement already satisfied: plotly>=3.8.1 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (6.0.1)
Requirement already satisfied: SALib>=1.3.3 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.5.2)
Requirement already satisfied: ipywidgets>=7.4.2 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (8.1.8)
Requirement already satisfied: aplr>=10.6.1 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (10.23.0)
Requirement already satisfied: dash>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2.18.1)
Requirement already satisfied: dash-cytoscape>=0.1.1 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.0.2)
Requirement already satisfied: flask>=1.0.4 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.0.3)
Requirement already satisfied: gevent>=1.3.6 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (26.5.0)
Requirement already satisfied: requests>=2.19.0 in /opt/conda/lib/python3.12/site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2.34.0)
Requirement already satisfied: Mako in /opt/conda/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /opt/conda/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: Werkzeug<3.1 in /opt/conda/lib/python3.12/site-packages (from dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.0.6)
Requirement already satisfied: dash-html-components==2.0.0 in /opt/conda/lib/python3.12/site-packages (from dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in /opt/conda/lib/python3.12/site-packages (from dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in /opt/conda/lib/python3.12/site-packages (from dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (5.0.0)
Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.12/site-packages (from dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (6.10.0)
Requirement already satisfied: retrying in /opt/conda/lib/python3.12/site-packages (from dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.4.2)
Requirement already satisfied: nest-asyncio in /opt/conda/lib/python3.12/site-packages (from dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.6.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (82.0.1)
Requirement already satisfied: Jinja2>=3.1.2 in /opt/conda/lib/python3.12/site-packages (from flask>=1.0.4->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /opt/conda/lib/python3.12/site-packages (from flask>=1.0.4->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /opt/conda/lib/python3.12/site-packages (from flask>=1.0.4->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (8.3.3)
Requirement already satisfied: blinker>=1.6.2 in /opt/conda/lib/python3.12/site-packages (from flask>=1.0.4->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.9.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /opt/conda/lib/python3.12/site-packages (from Werkzeug<3.1->dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.0.3)
Requirement already satisfied: greenlet>=3.2.2 in /opt/conda/lib/python3.12/site-packages (from gevent>=1.3.6->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.5.0)
Requirement already satisfied: zope.event in /opt/conda/lib/python3.12/site-packages (from gevent>=1.3.6->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (6.2)
Requirement already satisfied: zope.interface in /opt/conda/lib/python3.12/site-packages (from gevent>=1.3.6->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (8.5)
Requirement already satisfied: decorator in /opt/conda/lib/python3.12/site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (5.2.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.12/site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.12/site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.12/site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.12/site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.12/site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2.20.0)
Requirement already satisfied: stack_data in /opt/conda/lib/python3.12/site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /opt/conda/lib/python3.12/site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (5.15.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.7.0)
Requirement already satisfied: comm>=0.1.3 in /opt/conda/lib/python3.12/site-packages (from ipywidgets>=7.4.2->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /opt/conda/lib/python3.12/site-packages (from ipywidgets>=7.4.2->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /opt/conda/lib/python3.12/site-packages (from ipywidgets>=7.4.2->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.0.16)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/conda/lib/python3.12/site-packages (from jedi>=0.16->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas->shap) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas->shap) (2026.2)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.12/site-packages (from pexpect>4.3->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.7.0)
Requirement already satisfied: narwhals>=1.15.1 in /opt/conda/lib/python3.12/site-packages (from plotly>=3.8.1->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2.21.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.19.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests>=2.19.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.12/site-packages (from requests>=2.19.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.26.20)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests>=2.19.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2026.4.22)
Requirement already satisfied: matplotlib>=3.5 in /opt/conda/lib/python3.12/site-packages (from SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.10.9)
Requirement already satisfied: multiprocess in /opt/conda/lib/python3.12/site-packages (from SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.70.19)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (1.5.0)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.3.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn->shap) (3.6.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata->dash>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.23.1)
Requirement already satisfied: dill>=0.4.1 in /opt/conda/lib/python3.12/site-packages (from multiprocess->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.4.1)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (3.0.1)
Requirement already satisfied: pure_eval in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.8->interpret) (0.2.3)

In [2]:
from src.pipeline import Pipeline, Context                                                                                                                                                                                                                                                             
from src.pipeline_steps import Load, Preprocess, TrainBinaryClassifier, TrainRegressor, Predict, Report

In [3]:
import src.config as config

In [4]:
DATA_PATH = "s3://msds-26.2-data/clean/combined_recovery_data_aggregated_with_full_features.parquet"
                                                                                                                                                                                                                                                                                                         
ctx = Context() 
Pipeline(
    Load(recovery_data_source=config.YEARLY_RECOVERY_DATA_CSVS),
    Preprocess(),
    TrainBinaryClassifier(train_years=config.DEFAULT_TRAIN_YEARS, test_years=config.DEFAULT_TEST_YEARS, tune=False),
    TrainRegressor(train_years=config.DEFAULT_TRAIN_YEARS, test_years=config.DEFAULT_TEST_YEARS, tune=False),
    Predict(predict_channels=False, run_shap=False),
    Report(),
)(ctx)

[0]	validation_0-auc:0.96346	validation_0-aucpr:0.91667	validation_0-logloss:0.65771
[100]	validation_0-auc:0.98067	validation_0-aucpr:0.96956	validation_0-logloss:0.18089
[200]	validation_0-auc:0.98190	validation_0-aucpr:0.97144	validation_0-logloss:0.17636
[207]	validation_0-auc:0.98188	validation_0-aucpr:0.97141	validation_0-logloss:0.17668
[0]	validation_0-rmse:5.84147	validation_0-prob_mae:0.48368
[100]	validation_0-rmse:1.30106	validation_0-prob_mae:0.04089
[164]	validation_0-rmse:1.30800	validation_0-prob_mae:0.04116

In [5]:
ctx['df_recovery_preprocessed'].columns

['share_fba_rolling_52w',
 'prob_recovered_ewma_0.1',
 'weight_total_rolling_52w',
 'site_prob_disposal_week_ewma_0.1',
 'units_total_lag_52w',
 'gl_product_group',
 'site_prob_recovered_week_lag_13w',
 'weight_total_lag_52w',
 'share_retail_ewma_0.5',
 'weight_total_ewma_0.5',
 'cogs_total_lag_12w',
 'prob_disposal_lag_13w',
 'site_prob_warehouse_deals_and_gr_week_rolling_26w',
 'prob_liquidations_ewma_0.5',
 'share_retail_rolling_4w',
 'share_hazmat_rolling_26w',
 'prob_recovered_lag_1w',
 'units_total_lag_13w',
 'cogs_total_lag_13w',
 'site_prob_recovered_week_lag_4w',
 'share_fba_rolling_4w',
 'prob_disposal_lag_52w',
 'prob_donations_lag_52w',
 'prob_return_to_vendor_rolling_12w',
 'cogs_total_rolling_52w',
 'share_retail_rolling_26w',
 'share_fba_lag_4w',
 'site_prob_disposal_week_lag_13w',
 'prob_donations_rolling_52w',
 'prob_disposal_ewma_0.5',
 'site_prob_donations_week_lag_1w',
 'site_units_total_week_lag_4w',
 'prob_return_to_vendor_lag_1w',
 'site_units_total_week_lag_1w',
 'prob_donations_lag_12w',
 'prob_return_to_vendor_lag_4w',
 'cogs_total_rolling_26w',
 'site_weight_total_week_lag_12w',
 'prob_liquidations_rolling_12w',
 'prob_return_to_vendor_lag_13w',
 'site_prob_liquidations_week_rolling_52w',
 'prob_liquidations_lag_12w',
 'site_prob_return_to_vendor_week_lag_4w',
 'site_prob_liquidations_week_lag_13w',
 'site_prob_liquidations_week_lag_12w',
 'site_weight_total_week_lag_13w',
 'share_fba_rolling_26w',
 'site_prob_return_to_vendor_week_ewma_0.1',
 'share_fba_lag_13w',
 'share_food_rolling_26w',
 'site_prob_warehouse_deals_and_gr_week_lag_13w',
 'prob_recovered',
 'site_prob_donations_week_lag_52w',
 'share_food_lag_52w',
 'share_fba_lag_52w',
 'units_total_ewma_0.5',
 'prob_donations',
 'share_non_food_ewma_0.1',
 'site_prob_donations_week_rolling_26w',
 'site_prob_warehouse_deals_and_gr_week_ewma_0.1',
 'units_total_lag_1w',
 'site_prob_return_to_vendor_week_rolling_52w',
 'share_hazmat_rolling_12w',
 'site_prob_liquidations_week_lag_1w',
 'site_prob_donations_week_ewma_0.1',
 'units_total_lag_4w',
 'share_fba_lag_1w',
 'share_food_lag_12w',
 'cogs_total_rolling_4w',
 'share_non_food_rolling_4w',
 'hashed_fc',
 'site_prob_liquidations_week_lag_4w',
 'site_units_total_week_lag_52w',
 'prob_disposal_lag_1w',
 'cogs_total_lag_52w',
 'prob_liquidations_ewma_0.1',
 'prob_liquidations',
 'share_food_lag_13w',
 'prob_return_to_vendor_lag_52w',
 'share_hazmat_rolling_4w',
 'cogs_total_ewma_0.1',
 'share_non_food_rolling_12w',
 'share_pet_food_ewma_0.1',
 'site_prob_liquidations_week_rolling_4w',
 'country',
 'prob_return_to_vendor_rolling_4w',
 'prob_liquidations_rolling_26w',
 'prob_warehouse_deals_and_gr_lag_12w',
 'share_pet_food_rolling_12w',
 'site_prob_warehouse_deals_and_gr_week_rolling_4w',
 'share_hazmat_rolling_52w',
 'site_prob_warehouse_deals_and_gr_week_rolling_52w',
 'site_prob_recovered_week_lag_1w',
 'prob_warehouse_deals_and_gr_lag_4w',
 'prob_disposal_lag_4w',
 'share_fba',
 'prob_warehouse_deals_and_gr_rolling_26w',
 'share_pet_food_lag_4w',
 'prob_donations_rolling_4w',
 'share_retail_ewma_0.1',
 'share_pet_food_lag_12w',
 'site_prob_disposal_week_rolling_26w',
 'share_food_lag_1w',
 'prob_disposal_lag_12w',
 'site_prob_donations_week_lag_13w',
 'share_food_rolling_4w',
 'share_hazmat_ewma_0.1',
 'cogs_total_rolling_12w',
 'site_prob_disposal_week_lag_52w',
 'month',
 'site_units_total_week_lag_12w',
 'site_prob_disposal_week_lag_4w',
 'site_prob_donations_week_rolling_4w',
 'weight_total_ewma_0.1',
 'site_prob_recovered_week_lag_12w',
 'share_pet_food_lag_1w',
 'prob_recovered_lag_52w',
 'cogs_total_ewma_0.5',
 'site_prob_return_to_vendor_week_rolling_26w',
 'weight_total_lag_13w',
 'share_food_ewma_0.1',
 'share_non_food_lag_52w',
 'share_retail_lag_13w',
 'weight_total_rolling_12w',
 'share_retail',
 'prob_warehouse_deals_and_gr_ewma_0.1',
 'site_weight_total_week',
 'share_hazmat_lag_1w',
 'prob_warehouse_deals_and_gr_rolling_4w',
 'prob_liquidations_lag_4w',
 'units_total_rolling_12w',
 'share_hazmat_lag_52w',
 'prob_donations_rolling_12w',
 'share_non_food_rolling_52w',
 'prob_warehouse_deals_and_gr_ewma_0.5',
 'site_prob_return_to_vendor_week_lag_13w',
 'site_prob_disposal_week_rolling_52w',
 'prob_donations_rolling_26w',
 'units_total',
 'share_retail_lag_12w',
 'site_prob_donations_week_ewma_0.5',
 'share_non_food_lag_4w',
 'site_prob_return_to_vendor_week_rolling_12w',
 'site_prob_liquidations_week_ewma_0.1',
 'share_non_food_rolling_26w',
 'prob_liquidations_lag_1w',
 'prob_recovered_rolling_12w',
 'site_type',
 'share_hazmat_lag_12w',
 'prob_liquidations_rolling_4w',
 'site_prob_warehouse_deals_and_gr_week_rolling_12w',
 'week',
 'prob_disposal_rolling_26w',
 'prob_warehouse_deals_and_gr_lag_52w',
 'share_pet_food_lag_52w',
 'prob_warehouse_deals_and_gr_lag_13w',
 'share_food_ewma_0.5',
 'prob_disposal_rolling_4w',
 'prob_return_to_vendor_rolling_52w',
 'site_prob_recovered_week_rolling_52w',
 'site_prob_donations_week_lag_12w',
 'site_prob_warehouse_deals_and_gr_week_ewma_0.5',
 'prob_return_to_vendor_lag_12w',
 'prob_donations_ewma_0.5',
 'site_prob_return_to_vendor_week_lag_12w',
 'weight_total_lag_4w',
 'year',
 'prob_return_to_vendor',
 'site_prob_liquidations_week_ewma_0.5',
 'site_prob_return_to_vendor_week_lag_52w',
 'prob_disposal_rolling_12w',
 'site_prob_donations_week_lag_4w',
 'prob_donations_lag_1w',
 'site_prob_recovered_week_rolling_4w',
 'prob_return_to_vendor_rolling_26w',
 'prob_disposal',
 'site_weight_total_week_lag_4w',
 'site_units_total_week_lag_13w',
 'prob_warehouse_deals_and_gr_rolling_12w',
 'site_prob_return_to_vendor_week_lag_1w',
 'prob_return_to_vendor_ewma_0.5',
 'share_retail_lag_1w',
 'cogs_total_lag_4w',
 'site_prob_recovered_week_rolling_26w',
 'share_food_rolling_52w',
 'country_state',
 'site_prob_return_to_vendor_week_rolling_4w',
 'share_fba_lag_12w',
 'prob_warehouse_deals_and_gr_lag_1w',
 'share_pet_food',
 'avg_cogs_per_unit',
 'share_pet_food_ewma_0.5',
 'weight_total_lag_12w',
 'prob_liquidations_lag_13w',
 'prob_warehouse_deals_and_gr_rolling_52w',
 'share_retail_rolling_12w',
 'cogs_total',
 'prob_liquidations_lag_52w',
 'site_prob_warehouse_deals_and_gr_week_lag_52w',
 'units_total_ewma_0.1',
 'share_non_food_lag_1w',
 'prob_recovered_rolling_52w',
 'prob_donations_lag_4w',
 'share_pet_food_lag_13w',
 'weight_total_lag_1w',
 'share_pet_food_rolling_52w',
 'units_total_rolling_26w',
 'prob_liquidations_rolling_52w',
 'site_units_total_week',
 'share_fba_ewma_0.5',
 'site_units_share_week',
 'share_non_food_ewma_0.5',
 'site_prob_liquidations_week_rolling_26w',
 'site_prob_disposal_week_rolling_4w',
 'prob_warehouse_deals_and_gr',
 'share_food_rolling_12w',
 'site_weight_total_week_lag_52w',
 'share_fba_rolling_12w',
 'prob_donations_lag_13w',
 'share_retail_lag_4w',
 'share_hazmat_ewma_0.5',
 'prob_recovered_rolling_4w',
 'site_prob_donations_week_rolling_52w',
 'prob_recovered_ewma_0.5',
 'prob_recovered_lag_4w',
 'cogs_per_unit_weight',
 'share_food_lag_4w',
 'share_hazmat',
 'prob_disposal_rolling_52w',
 'share_retail_lag_52w',
 'site_prob_liquidations_week_lag_52w',
 'site_prob_donations_week_rolling_12w',
 'prob_recovered_lag_12w',
 'share_non_food',
 'weight_total',
 'cogs_total_lag_1w',
 'share_fba_ewma_0.1',
 'site_prob_warehouse_deals_and_gr_week_lag_4w',
 'site_prob_disposal_week_lag_1w',
 'site_prob_return_to_vendor_week_ewma_0.5',
 'units_total_rolling_4w',
 'units_total_rolling_52w',
 'weight_total_rolling_4w',
 'site_prob_liquidations_week_rolling_12w',
 'prob_return_to_vendor_ewma_0.1',
 'site_prob_warehouse_deals_and_gr_week_lag_12w',
 'site_prob_recovered_week_rolling_12w',
 'site_prob_recovered_week_lag_52w',
 'site_category',
 'share_hazmat_lag_4w',
 'site_prob_disposal_week_ewma_0.5',
 'weight_total_rolling_26w',
 'site_prob_warehouse_deals_and_gr_week_lag_1w',
 'avg_weight_per_unit',
 'prob_recovered_lag_13w',
 'site_prob_disposal_week_rolling_12w',
 'share_food',
 'prob_donations_ewma_0.1',
 'share_non_food_lag_13w',
 'share_pet_food_rolling_4w',
 'share_retail_rolling_52w',
 'prob_recovered_rolling_26w',
 'share_pet_food_rolling_26w',
 'share_hazmat_lag_13w',
 'site_weight_total_week_lag_1w',
 'units_total_lag_12w',
 'site_weight_share_week',
 'prob_disposal_ewma_0.1',
 'share_non_food_lag_12w',
 'site_prob_disposal_week_lag_12w']

In [6]:
ctx['df_recovery_preprocessed'].head()

shape: (5, 270)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ share_fba ┆ prob_reco ┆ weight_to ┆ site_prob ┆ … ┆ site_weig ┆ prob_disp ┆ share_non ┆ site_pro │
│ _rolling_ ┆ vered_ewm ┆ tal_rolli ┆ _disposal ┆   ┆ ht_share_ ┆ osal_ewma ┆ _food_lag ┆ b_dispos │
│ 52w       ┆ a_0.1     ┆ ng_52w    ┆ _week_ewm ┆   ┆ week      ┆ _0.1      ┆ _12w      ┆ al_week_ │
│ ---       ┆ ---       ┆ ---       ┆ a_0…      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ lag_12…  │
│ f64       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.014369  ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.017227  ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.009555  ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.060956  ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.046474  ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
ctx['predictions']

shape: (2_538_780, 13)
┌─────────────┬─────────────┬──────┬──────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ hashed_fc   ┆ gl_product_ ┆ year ┆ week ┆ … ┆ shap_baseli ┆ shap_devia ┆ rate_bucke ┆ volume_buc │
│ ---         ┆ group       ┆ ---  ┆ ---  ┆   ┆ ne_rate     ┆ tion_contr ┆ t          ┆ ket        │
│ str         ┆ ---         ┆ i64  ┆ f64  ┆   ┆ ---         ┆ ibution    ┆ ---        ┆ ---        │
│             ┆ f64         ┆      ┆      ┆   ┆ f64         ┆ ---        ┆ str        ┆ str        │
│             ┆             ┆      ┆      ┆   ┆             ┆ f64        ┆            ┆            │
╞═════════════╪═════════════╪══════╪══════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 14.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ <10        │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 15.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ <10        │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 16.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ <10        │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 22.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 10-100     │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 23.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 10-100     │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ …           ┆ …           ┆ …    ┆ …    ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ fff3d746510 ┆ 121.0       ┆ 2025 ┆ 48.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 100-1k     │
│ 4aa75ee0ca3 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 1d193398…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ fff3d746510 ┆ 121.0       ┆ 2025 ┆ 49.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 100-1k     │
│ 4aa75ee0ca3 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 1d193398…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ fff3d746510 ┆ 121.0       ┆ 2025 ┆ 50.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 100-1k     │
│ 4aa75ee0ca3 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 1d193398…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ fff3d746510 ┆ 121.0       ┆ 2025 ┆ 51.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 100-1k     │
│ 4aa75ee0ca3 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 1d193398…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ fff3d746510 ┆ 121.0       ┆ 2025 ┆ 52.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 100-1k     │
│ 4aa75ee0ca3 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 1d193398…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
└─────────────┴─────────────┴──────┴──────┴───┴─────────────┴────────────┴────────────┴────────────┘